apiVersion: v1
kind: Service
metadata:
  name: hello-world-node
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      name: helloworld
  selector:
    app: hello-world-node
